// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOdS8bLjbEoBJAlm52mSRGtdaZ9-WRQA',
    appId: '1:324573318375:web:6268ffeb580edd0668a642',
    messagingSenderId: '324573318375',
    projectId: 'kfupm-tram',
    authDomain: 'kfupm-tram.firebaseapp.com',
    storageBucket: 'kfupm-tram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjhcRv8x4ARSS0Ymh5ro_y7F5HtvMndk',
    appId: '1:324573318375:android:d83c3e59970a82dc68a642',
    messagingSenderId: '324573318375',
    projectId: 'kfupm-tram',
    storageBucket: 'kfupm-tram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qii86uljEohctMR9u3sWJvTH9QT9OqM',
    appId: '1:324573318375:ios:4cac6596bb8c8f8268a642',
    messagingSenderId: '324573318375',
    projectId: 'kfupm-tram',
    storageBucket: 'kfupm-tram.appspot.com',
    iosBundleId: 'com.ghassan.seniorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qii86uljEohctMR9u3sWJvTH9QT9OqM',
    appId: '1:324573318375:ios:4b45ca31e21d3fc668a642',
    messagingSenderId: '324573318375',
    projectId: 'kfupm-tram',
    storageBucket: 'kfupm-tram.appspot.com',
    iosBundleId: 'com.ghassan.seniorProject.RunnerTests',
  );
}
